spring:
  application:
    name: user-api
  data:
    mongodb:
      host: localhost
      port: 27017
      database: user-mongo
      authentication-database: admin
  rabbitmq:
    host: localhost
    port: 15672
    username: guest
    password: guest
    ssl:
      enabled: false

