services:
  mysql:
    image: mysql:8.0
    container_name: database-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dev
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    volumes:
      - mysql_db_data:/var/lib/mysql

volumes:
  mysql_db_data: