services:
  db:
    image: postgres:15
    container_name: pg-nodejs
    restart: always
    environment:
      POSTGRES_USER: vitor
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: crudnodejs
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: