services:
  mongo:
    image: mongodb/mongodb-community-server
    container_name: user-database
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/root/.data

  rabbitmq:
    image: rabbitmq:management
    container_name: user-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/libs/.data

volumes:
  mongo_data:
  rabbitmq_data: